MvcFilmDunyasi/Models/ErrorViewModel.cs
namespace MvcFilmDunyasi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcFilmDunyasi/Models/FilmDuzenleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MvcFilmDunyasi.Models
{
    public class FilmDuzenleViewModel
    {
        public int Id { get; set; }

        [MaxLength(400)]
        public string Ad { get; set; } = null!;

        public int Yil { get; set; }
        [Required]
        public decimal? Puan { get; set; }
        public int[] Turler { get; set; } = Array.Empty<int>();
    }
}

MvcFilmDunyasi/Models/HomeViewModel.cs
using MvcFilmDunyasi.Data;

namespace MvcFilmDunyasi.Models
{
    public class HomeViewModel
    {
        public List<Film> Filmler { get; set; } = new();
        public int? TurId { get; set; }
    }
}

MvcFilmDunyasi/Models/YeniFilmViewModel.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace MvcFilmDunyasi.Models
{
    public class YeniFilmViewModel
    {
        [MaxLength(400)]
        public string Ad { get; set; } = null!;

        public int Yil { get; set; }
        [Required]
        public decimal? Puan { get; set; }
        public int[] Turler { get; set; } = Array.Empty<int>();
    }
}

MvcFilmDunyasi/Controllers/FilmlerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcFilmDunyasi.Data;
using MvcFilmDunyasi.Models;

namespace MvcFilmDunyasi.Controllers
{
    public class FilmlerController : Controller
    {
        private readonly UygulamaDbContext _db;

        public FilmlerController(UygulamaDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.Filmler.Include(x=>x.Turler).ToList());
        }

        public IActionResult Yeni()
        {
            ViewBag.Turler = _db.Turler.ToList();
            var vm = new YeniFilmViewModel();
            return View(vm);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Yeni(YeniFilmViewModel vm)
        {
            if (ModelState.IsValid)
            {
                Film film = new Film()
                {
                    Ad = vm.Ad,
                    Puan = vm.Puan!.Value,
                    Yil = vm.Yil,
                    Turler = _db.Turler.Where(x => vm.Turler.Contains(x.Id)).ToList()
                };
                _db.Filmler.Add(film);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Turler = _db.Turler.ToList();
            return View(vm);
        }

        public IActionResult Duzenle(int id)
        {

            var film = _db.Filmler.Include(x => x.Turler).FirstOrDefault(x => x.Id == id);

            if (film == null)
                return NotFound();

            var vm = new FilmDuzenleViewModel()
            {
                Id = film.Id,
                Ad = film.Ad,
                Puan = film.Puan,
                Yil = film.Yil,
                Turler = film.Turler.Select(x => x.Id).ToArray()

            };

            ViewBag.Turler = _db.Turler.ToList();
            return View(vm);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public IActionResult Duzenle(FilmDuzenleViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var film = _db.Filmler.Find(vm.Id);
                if (film == null)
                    return NotFound();

                _db.Entry(film).Collection(x => x.Turler).Load();

                film.Id=vm.Id;
                film.Ad = vm.Ad;
                film.Puan = vm.Puan!.Value;
                film.Turler.Clear();
                film.Turler = _db.Turler.Where(x => vm.Turler.Contains(x.Id)).ToList();
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Turler = _db.Turler.ToList();
            return View(vm);
        }

        public IActionResult Sil(int id)
        {
            Film? film = _db.Filmler.Find(id);
            if (film == null)
                return NotFound();
            return View(film);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SilOnay(int id)
        {
            Film? film = _db.Filmler.Find(id);
            if (film == null)
                return NotFound();
            _db.Remove(film);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcFilmDunyasi/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcFilmDunyasi.Data;
using MvcFilmDunyasi.Models;
using System.Diagnostics;

namespace MvcFilmDunyasi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UygulamaDbContext _db;

        public HomeController(ILogger<HomeController> logger, UygulamaDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public IActionResult Index(int? turId)
        {
            IQueryable<Film> filmler = _db.Filmler.Include(x=>x.Turler);

            if(turId != null)
            {
                //öyle filmleri getir ki o filmin türlerinin en az birisinin id 'si turId'ye eşit olsun
                filmler = filmler.Where(x => x.Turler.Any(t => t.Id == turId));
            }

            ViewBag.Turler = _db.Turler.Select(x => new SelectListItem()
            {
                Text = x.Ad,
                Value = x.Id.ToString()
            }).ToList();

            var vm = new HomeViewModel()
            {
                Filmler = filmler.ToList(),
                TurId = turId
            };

            return View(vm);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcFilmDunyasi/Views/Filmler/Duzenle.cshtml
@using MvcFilmDunyasi.Data
@model FilmDuzenleViewModel
@{
    ViewBag.Title = "Düzenle";
}

<form asp-controller="Filmler" asp-action="Duzenle" method="post">
    <input asp-for="Id" type="hidden" />
    <div class="mb-2">
        <label asp-for="Ad"></label>
        <input asp-for="Ad" class="form-control" type="text" />
        <span asp-validation-for="Ad" class="text-danger"></span>
    </div>
    <div class="mb-2">
        <label asp-for="Yil"></label>
        <input asp-for="Yil" class="form-control" type="text" />
        <span asp-validation-for="Yil" class="text-danger"></span>
    </div>
    <div class="mb-2">
        <label asp-for="Puan"></label>
        <input asp-for="Puan" class="form-control" type="text" />
        <span asp-validation-for="Puan" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <div class="row">
            @foreach (Tur tur in ViewBag.Turler)
            {
                <div class="col-6 col-sm-4 col-md-3 col-lg-2">
                    <label class="d-flex align-items-center">
                        <input type="checkbox" name="turler" value="@tur.Id" class="me-1" @(Model.Turler.Contains(tur.Id) ? "checked":"") />
                        @tur.Ad
                    </label>
                </div>
            }
        </div>

    </div>
    <button class="btn btn-success">Kaydet</button>
</form>

MvcFilmDunyasi/Views/Filmler/Index.cshtml
@using MvcFilmDunyasi.Data
@model List<Film>

@{
    ViewBag.Title = "Filmler";
}

<h1>Filmler</h1>

<a asp-action="Yeni" class="btn btn-primary">Film Ekle</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Film Adı</th>
            <th>Yıl</th>
            <th>Puan</th>
            <th>Türler</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Film film in Model)
        {
            <tr>
                <td>@film.Id</td>
                <td>@film.Ad</td>
                <td>@film.Yil</td>
                <td>@film.Puan</td>
                <td>
                    @string.Join(", ", film.Turler.Select(x => x.Ad))
                </td>
                <td>
                    <a asp-action="Duzenle" asp-route-id="@film.Id">Düzenle</a>
                    <a asp-action="Sil" asp-route-id="@film.Id">Sil</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MvcFilmDunyasi/Views/Filmler/Sil.cshtml
@using MvcFilmDunyasi.Data
@model Film
@{
    ViewBag.Title = "Sil";
}

<form asp-action="SilOnay" asp-controller="Filmler" method="post">
    <input asp-for="Id" type="hidden" />
    <p>@Model.Ad (@Model.Yil) (@Model.Puan) filmini silmek istiyor musunuz?</p>
    <div>
        <button class="btn btn-primary">Evet</button>
        <a asp-action="Index" class="btn btn-danger">Vazgeç</a>
    </div>
</form>

MvcFilmDunyasi/Views/Filmler/Yeni.cshtml
@using MvcFilmDunyasi.Data
@model YeniFilmViewModel
@{
    ViewBag.Title = "Yeni Film";
}

<h1>Yeni Film</h1>

<form asp-controller="Filmler" asp-action="Yeni" method="post">
    <div class="mb-2">
        <label asp-for="Ad"></label>
        <input asp-for="Ad" class="form-control" type="text"/>
        <span asp-validation-for="Ad" class="text-danger"></span>
    </div>
    <div class="mb-2">
        <label asp-for="Yil"></label>
        <input asp-for="Yil" class="form-control" type="text" />
        <span asp-validation-for="Yil" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Puan"></label>
        <input asp-for="Puan" class="form-control" type="text" />
        <span asp-validation-for="Puan" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <div class="row">
            @foreach (Tur tur in ViewBag.Turler)
            {
                <div class="col-6 col-sm-4 col-md-3 col-lg-2">
                    <label class="d-flex align-items-center">
                        <input type="checkbox" name="turler" value="@tur.Id" class="me-1" @(Model.Turler.Contains(tur.Id)? "checked":"")/>
                        @tur.Ad
                    </label>
                </div>
            }
        </div>
       
    </div>
    <button class="btn btn-primary">Ekle</button>
</form>

MvcFilmDunyasi/Views/Home/Index.cshtml
@model HomeViewModel;

@{
    ViewData["Title"] = "Home Page";
}

<form method="get" class="d-flex">
    <select asp-for="TurId" class="form-select me-2 flex-grow-1" asp-items="ViewBag.Turler">
        <option value="">Tümü</option>
    </select>
    <button class="btn btn-primary">Listele</button>
</form>



<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Film Adı</th>
            <th>Yıl</th>
            <th>Puan</th>
            <th>Türler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var film in Model.Filmler)
        {
            <tr>
                <td>@film.Id</td>
                <td>@film.Ad</td>
                <td>@film.Yil</td>
                <td>@film.Puan</td>
                <td>
                    @string.Join(", ", film.Turler.Select(x => x.Ad))
                </td>
            </tr>
        }
    </tbody>
</table>

MvcFilmDunyasi/Views/Home/Index1.cshtml
@using MvcFilmDunyasi.Data
@model List<Film>;

@{
    ViewData["Title"] = "Home Page";
};

<select asp-items="ViewBag.Turler">
    <option>Tümü</option>
</select>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Film Adı</th>
            <th>Yıl</th>
            <th>Puan</th>
            <th>Türler</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Film film in Model)
        {
            <tr>
                <td>@film.Id</td>
                <td>@film.Ad</td>
                <td>@film.Yil</td>
                <td>@film.Puan</td>
                <td>
                    @string.Join(", ", film.Turler.Select(x => x.Ad))
                </td>
            </tr>
        }
    </tbody>
</table>

MvcFilmDunyasi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcFilmDunyasi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcFilmDunyasi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcFilmDunyasi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filmler" asp-action="Index">Filmler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcFilmDunyasi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>